### ISSUE TITLE
Error when trying to open save file to edit.

### ISSUE THREAD

**Issue by Denzel-Washingmachine** [scottanderson/railroad.studio#92] opened 2023-12-12 22:55 UTC
This maybe just be because of the most recent update to the game but I tried opening a save file and got the error: 
Failed to load: Error: Unexpected GUID: 69981E2B47B2AABC01CE39842FB03A96
Error: Unexpected GUID: 69981E2B47B2AABC01CE39842FB03A96
    at Pn (https://railroad.studio/studio.js:1:130207)
    at https://railroad.studio/studio.js:1:212385
    at Array.flatMap (<anonymous>)
    at new es (https://railroad.studio/studio.js:1:212209)
    at https://railroad.studio/studio.js:1:270240
    at https://railroad.studio/studio.js:1:258437

**Comment by scottanderson** [comment] 2023-12-13 03:13
Duplicate of #91

**Closed as not planned by scottanderson** 2023-12-13 03:13 UTC
Labels: bug
