### ISSUE TITLE
replanting trees

### ISSUE THREAD

**Issue by jaltadonna** [scottanderson/railroad.studio#114] opened 2024-01-17 01:55 UTC
You cannot replant trees at all you can cut them all down but not replant them.
I could not give you my .sav file this does not suport it.

**Comment by illudedPerception** [comment] 2024-01-27 17:05
the tree tools not updated, yet

**Comment by scottanderson** [comment] 2024-01-27 22:08
Closing as a duplicate of #41.

As I noted in the very first line of the new issue template, you will need to zip save files before you can attach them to a github issue.

**Closed as completed by scottanderson** 2024-01-27 22:08 UTC
Labels: bug
