### ISSUE TITLE
Failed to load: Error: Some frame values are missing

### ISSUE THREAD

**Issue by theoldyellowcab** [scottanderson/railroad.studio#76] opened 2023-11-25 16:29 UTC
**Describe the bug**

```
Failed to load: Error: Some frame values are missing
    at https://railroad.studio/studio.js:1:259612
    at https://railroad.studio/studio.js:1:266720
    at https://railroad.studio/studio.js:1:255478
```

**To Reproduce**
Try to load a save game from version 0.6.0.0.3

**Expected behavior**
Save game loads

**Additional context**

I think this issue might be related to the missing passenger car issue that was encountered during the initial phase of 0.6.0.0.3. I purchased 3 coaches before the update and there are 3 frame value errors in the message.

**Comment by scottanderson** [comment] 2023-11-25 17:46
This error happens because `FreightTypeArray` was replaced with `FreightTypes`. Marking this as a dupe of #63, please see [milestone 1] for a breakdown of the remaining work.

[milestone 1]: https://github.com/scottanderson/railroad.studio/milestone/1

**Closed as not planned by scottanderson** 2023-11-25 17:46 UTC
